### ISSUE TITLE
path 

### ISSUE THREAD

**Issue by mttomzeh** [devolart/rclone-index#1]
hi 
possible to fix path folders, for ex from "https://rclone-index.glitch.me/%5Bhome:%5D/" to "https://rclone-index.glitch.me/home/"
thanks

**Comment by raffiihza** [comment]
Sorry for late response. The default behavior from rclone rcd is like that. If you want to make the links like that, change the code from `rclone rcd` to `rclone serve`. But the downside of `rclone serve` is that it can only show one remote at a time, unlike `rclone rcd` that shows all remotes you have. Though you can also make a combine config to make them all seen as folders.

I think there is a method to combine the remotes manually. I'll consider your request and try that method. If that works, I'll update it.

**Comment by devolart** [comment]
Sorry for late response. The default behavior from `rclone rcd` is like that. If you want to make the links like that, change the code from `rclone rcd` to `rclone serve`. But the downside of `rclone serve` is that it can only show one remote at a time, unlike `rclone rcd` that shows all remotes you have. Though you can also make a combine config to make them all seen as folders.

I think there is a method to combine the remotes automatically*. I'll consider your request and try that method. If that works, I'll update it.

**Comment by devolart** [comment]
Ok it's done, please test it. If it works properly, then I'll close this issue

**Comment by Davendx** [comment]
I just tested it, and it works fine now
Thank you

**Comment by mttomzeh** [comment]
its match with Rclone MLTB,
Thank you
